### ISSUE TITLE
Update `semver` dep in primary dependencies of @npm/cli

### ISSUE THREAD

**Issue by mikemimik** [npm/node-semver#289]
## Task
Update the `semver` package in all primary dependencies of [npm/cli](https://github.com/npm/cli)

## Primary Packages with Semver Dep
| Completed | Package Name | Semver Range | Current Version | Next Version<br />_(with semver bump)_ |
|---|---|---|---|---|
| <ul><li>[x] [PR](https://github.com/npm/init-package-json/pull/86)</li><li>[ ] Landed</li><li>[ ] Released</li></ul> | [init-package-json](https://github.com/npm/init-package-json) | `^1.10.3` | `1.10.3` | 
| <ul><li>[x] [PR](https://github.com/npm/lock-verify/pull/5)</li><li>[ ] Landed</li><li>[ ] Released</li></ul> | [lock-verify](https://github.com/npm/lock-verify) | `^2.1.0` | `2.1.0` | 
| <ul><li>[x] [PR](https://github.com/npm/normalize-package-data/pull/102)</li><li>[ ] Landed</li><li>[ ] Released</li></ul> | [normalize-package-data](https://github.com/npm/normalize-package-data) | `^2.5.0` | `2.5.0` | 
| <ul><li>[x] [PR](https://github.com/npm/npm-install-checks/pull/5)</li><li>[ ] Landed</li><li>[ ] Released</li></ul> | [npm-install-checks](https://github.com/npm/npm-install-checks) | `~3.0.0` | `3.0.0` | 
| <ul><li>[x] [PR](https://github.com/npm/npm-package-arg/pull/41)</li><li>[ ] Landed</li><li>[ ] Released</li></ul> | [npm-package-arg](https://github.com/npm/npm-package-arg) | `^6.1.1` | `6.1.1` | 
| <ul><li>[x] PR</li><li>[ ] Landed</li><li>[ ] Released</li></ul> | [npm-pick-manifest](https://github.com/npm/npm-pick-manifest) | `^3.0.2` | `3.0.2` | 
| <ul><li>[x] PR</li><li>[x] Landed</li><li>[x] Released</li></ul> | [pacote](https://github.com/npm/pacote) | `^9.5.8` | `9.5.8` | 
| <ul><li>[x] PR</li><li>[ ] Landed</li><li>[ ] Released</li></ul> | [read-installed](https://github.com/npm/read-installed) | `~4.0.3` | `4.0.3` | 
## Upstream Packages with Semver Dep
| Completed | Package Name | Semver Range | Current Version | Next Version<br />_(with semver bump)_ |
|---|---|---|---|---|
| <ul><li>[ ] PR</li><li>[ ] Landed</li><li>[ ] Released</li></ul> | [node-gyp](https://github.com/nodejs/node-gyp) | `^5.0.3` | `5.0.3` | 

#### Primary dependencies
- [ ] init-package-json
- [ ] lock-verify
- [ ] normalize-package-data
- [ ] npm-install-checks
- [ ] npm-package-arg
- [ ] npm-pick-manifest
- [x] pacote
- [ ] read-installed

#### Upstream dependency will need external pull-request
- [ ] node-gyp [upstream]

**Comment by mikemimik** [comment]
Note to self: don't forget to update `.travis.yml` file in all places touched, as well as the `CHANGELOG.md` file in all places touched.

**Comment by isaacs** [comment]
Note: these should be updated to semver 7 now that that's out, not 6.3.0.  Happy to make the change when landing.

**Comment by isaacs** [comment]
Everything in the `release/v7.0.0-beta` branch is now using the latest semver.
