### ISSUE TITLE
[TRACKING] `semver@8`

### ISSUE THREAD

**Issue by darcyclarke** [npm/node-semver#501]
### (WIP)

This is a tracking issue & WIP set of potential breaking changes, features & bugs which are expected to be fixed in the next major version of `semver`.

#### Breaking Changes
- [ ] [Remove preload](https://github.com/npm/node-semver/blob/940723d22bca824993627c45ac30dd3d2854b8cd/preload.js#L1)
- [ ] [Rewrite the cli](https://github.com/npm/node-semver/issues/499)
- [ ] Bump engines
- [ ] [Rearrange files for better import experience](https://github.com/npm/node-semver/issues/498)
- [ ] #418 
- [ ] #378 
- [ ] #691

#### Bugs
- [ ] #108 
- [ ] #381 
- [ ] #458 
- [x] #376 
- [ ] #354 
- [ ] #483 
- [ ] #345

**Comment by budarin** [comment]
Consider storing versions internally not in a string representation

https://marvinh.dev/blog/speeding-up-javascript-ecosystem/
please look at the paragraph "The curious case of semver"

**Comment by Mister-Hope** [comment]
Hi, is there any release table for v8? I believe this could be added.

Asking because I am trying to replace some outdated deps from repos I am maintaining. server v7 is requiring on a "very old" version of lru-cache.

**Comment by 7814222651** [comment]
Pay 💰 50000
Please please plz pls sir sir 😭🧠💔🙏🏻🙏🏻🤝🤝🫡📱
![Uploading BA16C54F-779C-425F-B499-5D20B5DFAEBE.jpeg…]()

**Comment by 7814222651** [comment]
![729A6456-DA74-4319-A327-AFBB1B4F896B](https://github.com/user-attachments/assets/eeeeff7f-8850-47b9-bdfb-b00835fdd398)
