### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by Gornator** [npm/node-semver#581]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm:
- Node:
- OS:
- platform:

```[tasklist]
### Tasks
- [ ] YOLO
- [ ] https://github.com/npm/node-semver/pull/571
- [ ] https://github.com/npm/node-semver/pull/568
- [ ] https://github.com/npm/node-semver/pull/548
- [ ] https://github.com/npm/node-semver/pull/569
- [ ] https://github.com/npm/node-semver/pull/564
- [ ] https://github.com/npm/node-semver/issues/580
- [ ] https://github.com/npm/node-semver/issues/579
- [ ] https://github.com/npm/node-semver/issues/578
- [ ] https://github.com/npm/node-semver/pull/575
- [ ] https://github.com/npm/node-semver/pull/559
- [ ] https://github.com/npm/node-semver/issues/577
- [ ] https://github.com/npm/node-semver/issues/576
- [ ] https://github.com/npm/node-semver/pull/574
- [ ] https://github.com/npm/node-semver/pull/570
- [ ] https://github.com/npm/node-semver/issues/573
- [ ] https://github.com/npm/node-semver/issues/275
- [ ] https://github.com/npm/node-semver/pull/566
- [ ] https://github.com/npm/node-semver/pull/565
```

```[tasklist]
### Tasks
- [ ] https://github.com/npm/node-semver/pull/571
- [ ] https://github.com/npm/node-semver/pull/568
- [ ] https://github.com/npm/node-semver/pull/548
```

```[tasklist]
### Tasks
```
